// SPDX-License-Identifier: PMPL-1.0-or-later
// Copyright (c) 2026 Jonathan D.A. Jewell <j.d.a.jewell@open.ac.uk>
//
// Wrapper generator module for ephapaxiser — Generates Ephapax linear type wrappers.
//
// Produces Rust-style ownership wrapper code that enforces exactly-once usage of resources.
// Each resource definition from the manifest gets a wrapper struct that:
// - Takes ownership of the raw resource handle on creation (allocation)
// - Provides a `consume` method that deallocates and invalidates the wrapper
// - Implements Drop to detect leaks at runtime (panics if not explicitly consumed)
// - Does NOT implement Clone or Copy (linear: exactly one owner)
//
// The generated code is standalone and can be compiled into the user's project.

use crate::manifest::ResourceEntry;

/// Generate Ephapax linear type wrapper code for a set of resource definitions.
///
/// Returns a complete Rust source file as a string, containing one wrapper struct
/// per resource definition.
///
/// # Arguments
/// * `resources` — Resource definitions from the manifest.
/// * `project_name` — Project name (for the module header comment).
///
/// # Returns
/// A String containing valid Rust source code.
pub fn generate_wrappers(resources: &[ResourceEntry], project_name: &str) -> String {
    let mut output = String::new();

    // File header.
    output.push_str(&format!(
        "// SPDX-License-Identifier: PMPL-1.0-or-later\n\
         // Auto-generated by ephapaxiser for project: {}\n\
         //\n\
         // Ephapax linear type wrappers — each resource must be used exactly once.\n\
         // Do NOT implement Clone or Copy on these types. That would break linearity.\n\
         //\n\
         // Design note: When Idris2 proofs conflict with Ephapax linear types, Idris2 ALWAYS wins.\n\
         \n\
         use std::marker::PhantomData;\n\
         \n",
        project_name
    ));

    for resource in resources {
        output.push_str(&generate_single_wrapper(resource));
        output.push('\n');
    }

    output
}

/// Generate the wrapper code for a single resource.
fn generate_single_wrapper(resource: &ResourceEntry) -> String {
    let type_name = &resource.name;
    let alloc_fn = &resource.allocator;
    let dealloc_fn = &resource.deallocator;
    let kind = &resource.kind;

    // Sanitise the type name for use as a Rust identifier (replace hyphens with underscores).
    let safe_type_name = type_name.replace('-', "_");
    let wrapper_name = format!("Linear{}", safe_type_name);
    let consumed_field = "consumed";

    format!(
        "/// Linear wrapper for `{type_name}` ({kind} resource).\n\
         ///\n\
         /// Allocated by `{alloc_fn}()`, deallocated by `{dealloc_fn}()`.\n\
         /// This wrapper enforces exactly-once usage: the resource MUST be consumed\n\
         /// by calling `.consume()`. Dropping without consuming will panic.\n\
         ///\n\
         /// NOT Clone, NOT Copy — linear ownership only.\n\
         pub struct {wrapper_name}<T> {{\n\
         {indent}/// The underlying resource handle.\n\
         {indent}inner: Option<T>,\n\
         {indent}/// Whether this resource has been properly consumed.\n\
         {indent}{consumed_field}: bool,\n\
         {indent}/// Prevent auto-traits from being derived.\n\
         {indent}_marker: PhantomData<*const ()>,\n\
         }}\n\
         \n\
         impl<T> {wrapper_name}<T> {{\n\
         {indent}/// Wrap a raw resource handle, taking ownership.\n\
         {indent}///\n\
         {indent}/// The caller transfers ownership of `raw` to this wrapper.\n\
         {indent}/// The resource MUST be consumed exactly once via `.consume()`.\n\
         {indent}///\n\
         {indent}/// # Arguments\n\
         {indent}/// * `raw` — The raw resource handle from `{alloc_fn}()`.\n\
         {indent}pub fn new(raw: T) -> Self {{\n\
         {indent}{indent}Self {{\n\
         {indent}{indent}{indent}inner: Some(raw),\n\
         {indent}{indent}{indent}{consumed_field}: false,\n\
         {indent}{indent}{indent}_marker: PhantomData,\n\
         {indent}{indent}}}\n\
         {indent}}}\n\
         \n\
         {indent}/// Borrow the inner resource handle (read-only).\n\
         {indent}///\n\
         {indent}/// This does NOT consume the resource. The wrapper retains ownership.\n\
         {indent}///\n\
         {indent}/// # Panics\n\
         {indent}/// Panics if the resource has already been consumed.\n\
         {indent}pub fn borrow(&self) -> &T {{\n\
         {indent}{indent}self.inner.as_ref().expect(\"{wrapper_name}: use-after-free — resource already consumed\")\n\
         {indent}}}\n\
         \n\
         {indent}/// Consume the resource, returning the raw handle for deallocation.\n\
         {indent}///\n\
         {indent}/// After calling this, the wrapper is empty and will not panic on drop.\n\
         {indent}/// The caller MUST pass the returned handle to `{dealloc_fn}()`.\n\
         {indent}///\n\
         {indent}/// # Panics\n\
         {indent}/// Panics if the resource has already been consumed (double-free).\n\
         {indent}pub fn consume(mut self) -> T {{\n\
         {indent}{indent}assert!(!self.{consumed_field}, \"{wrapper_name}: double-free — resource already consumed\");\n\
         {indent}{indent}self.{consumed_field} = true;\n\
         {indent}{indent}self.inner.take().expect(\"{wrapper_name}: internal error — inner was None\")\n\
         {indent}}}\n\
         }}\n\
         \n\
         impl<T> Drop for {wrapper_name}<T> {{\n\
         {indent}/// Drop check: panics if the resource was not explicitly consumed.\n\
         {indent}///\n\
         {indent}/// This catches resource leaks at runtime. In production, you may want to\n\
         {indent}/// log instead of panic — but for correctness checking, panic is appropriate.\n\
         {indent}fn drop(&mut self) {{\n\
         {indent}{indent}if !self.{consumed_field} && self.inner.is_some() {{\n\
         {indent}{indent}{indent}eprintln!(\"EPHAPAX VIOLATION: {wrapper_name} dropped without being consumed (resource leak)\");\n\
         {indent}{indent}{indent}// In debug builds, panic to catch leaks early.\n\
         {indent}{indent}{indent}#[cfg(debug_assertions)]\n\
         {indent}{indent}{indent}panic!(\"{wrapper_name}: resource leak — allocated but never consumed via .consume()\");\n\
         {indent}{indent}}}\n\
         {indent}}}\n\
         }}\n",
        type_name = type_name,
        kind = kind,
        alloc_fn = alloc_fn,
        dealloc_fn = dealloc_fn,
        wrapper_name = wrapper_name,
        consumed_field = consumed_field,
        indent = "    ",
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper to create a resource entry.
    fn res(name: &str, alloc: &str, dealloc: &str, kind: &str) -> ResourceEntry {
        ResourceEntry {
            name: name.to_string(),
            allocator: alloc.to_string(),
            deallocator: dealloc.to_string(),
            kind: kind.to_string(),
        }
    }

    #[test]
    fn test_generate_produces_wrappers() {
        let resources = vec![
            res("FileHandle", "open", "close", "file-descriptor"),
            res("DbConnection", "connect", "disconnect", "db-connection"),
        ];
        let output = generate_wrappers(&resources, "test-project");

        // Verify header.
        assert!(output.contains("Auto-generated by ephapaxiser"));
        assert!(output.contains("test-project"));

        // Verify wrapper structs exist.
        assert!(output.contains("pub struct LinearFileHandle<T>"));
        assert!(output.contains("pub struct LinearDbConnection<T>"));

        // Verify key methods exist.
        assert!(output.contains("pub fn new(raw: T) -> Self"));
        assert!(output.contains("pub fn consume(mut self) -> T"));
        assert!(output.contains("pub fn borrow(&self) -> &T"));

        // Verify Drop implementation exists.
        assert!(output.contains("impl<T> Drop for LinearFileHandle<T>"));
        assert!(output.contains("impl<T> Drop for LinearDbConnection<T>"));

        // Verify NOT Clone/Copy (these should NOT appear).
        assert!(!output.contains("impl<T> Clone"));
        assert!(!output.contains("impl<T> Copy"));

        // Verify allocator/deallocator names are referenced in docs.
        assert!(output.contains("open()"));
        assert!(output.contains("close()"));
        assert!(output.contains("connect()"));
        assert!(output.contains("disconnect()"));
    }

    #[test]
    fn test_generate_empty_resources() {
        let output = generate_wrappers(&[], "empty-project");
        assert!(output.contains("Auto-generated by ephapaxiser"));
        // No wrapper structs should be present.
        assert!(!output.contains("pub struct Linear"));
    }

    #[test]
    fn test_generate_custom_kind() {
        let resources = vec![res("GpuTensor", "alloc_tensor", "free_tensor", "gpu-buffer")];
        let output = generate_wrappers(&resources, "gpu-project");
        assert!(output.contains("pub struct LinearGpuTensor<T>"));
        assert!(output.contains("gpu-buffer resource"));
    }
}
